version: "3"
services:
  fieldy_container:
    container_name: fieldy_container
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fieldy:latest
    volumes:
      - ./server:/app/server
    working_dir: /app
    ports:
      - "4001:4001"